# Generated by Django 5.0.3 on 2024-03-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_remove_note_created_remove_note_done_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='quote',
        ),
    ]
