# Generated by Django 5.0.3 on 2024-03-24 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_rename_description_note_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='noteapp.author'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
