# Generated by Django 5.0.3 on 2024-03-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0005_note_author_remove_note_tags_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='quote',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True),
        ),
    ]
